const Homeproducts=[
    {
        id:1,
        image:"/images/home-slide-images/pan-corner.webp",
        to:"/paan-corner"
    },
    {
        id:2,
        image:"/images/home-slide-images/aata-rice.webp",
        to:"/aata"
    },
    {
        id:3,
        image:"/images/home-slide-images/baby-care.webp",
        to:"/baby-care"
    },
    {
        id:4,
        image:"/images/home-slide-images/bakery.webp",
        to:"/bakery-biscuits"
    },
    {
        id:5,
        image:"/images/home-slide-images/breakfast.webp",
        to:"/breakfast-instantfood"
    },
    {
        id:6,
        image:"/images/home-slide-images/chicken-meat.webp",
        to:"/chicken-meat"
    },
    {
        id:7,
        image:"/images/home-slide-images/petcare.webp",
        to:"/pet-care"
    },
    {
        id:8,
        image:"/images/home-slide-images/pharma.webp",
        to:"/pharmacy-products"
    },
    {
        id:9,
        image:"/images/home-slide-images/dairy-bread.webp",
        to:"/dairy-bread-eggs"
    },
    {
        id:10,
        image:"/images/home-slide-images/cleaning.webp",
        to:"/cleaning-products"
    },
]
export default Homeproducts