const Homeproducts=[
    {
        id:1,
        image:"/images/home-slide-images/pan-corner.webp"
    },
    {
        id:2,
        image:"/images/home-slide-images/aata-rice.webp"
    },
    {
        id:3,
        image:"/images/home-slide-images/baby-care.webp"
    },
    {
        id:4,
        image:"/images/home-slide-images/bakery.webp"
    },
    {
        id:5,
        image:"/images/home-slide-images/breakfast.webp"
    },
    {
        id:6,
        image:"/images/home-slide-images/chicken-meat.webp"
    },
    {
        id:7,
        image:"/images/home-slide-images/cleaning.webp"
    },
    {
        id:8,
        image:"/images/home-slide-images/cold-drinks.webp"
    },
    {
        id:9,
        image:"/images/home-slide-images/dairy-bread.webp"
    },
    {
        id:10,
        image:"/images/home-slide-images/fruits-veg.webp"
    },
    {
        id:11,
        image:"/images/home-slide-images/home-office.webp"
    },
    {
        id:12,
        image:"/images/home-slide-images/masala-oil.webp"
    },
    {
        id:13,
        image:"/images/home-slide-images/organic.webp"
    },
    {
        id:14,
        image:"/images/home-slide-images/personal-care.webp"
    },
    {
        id:15,
        image:"/images/home-slide-images/petcare.webp"
    },
    {
        id:16,
        image:"/images/home-slide-images/pharma.webp"
    },
    {
        id:17,
        image:"/images/home-slide-images/sauce.webp"
    },
    {
        id:18,
        image:"/images/home-slide-images/snacks.webp"
    },
    {
        id:19,
        image:"/images/home-slide-images/sweet.webp"
    },
    {
        id:20,
        image:"/images/home-slide-images/tea-coffee.webp"
    },
]
export default Homeproducts